from __future__ import annotations
import json,sqlite3
from pathlib import Path
def build(media_root:Path,runtime:Path):
 c=sqlite3.connect(media_root/'.scene_brain/catalog.db');c.row_factory=sqlite3.Row;titles=[]
 for t in c.execute('select * from titles order by display_name'):
  sources=[dict(x) for x in c.execute('select relative_path,subtitle_status,maturity,duration_ms from sources where title_id=? and present=1 order by relative_path',(t['title_id'],))];titles.append({**dict(t),'sources':sources})
 manifest=json.loads((media_root/'.scene_brain/volume_manifest.json').read_text());c.close();data=json.dumps({'manifest':manifest,'titles':titles},separators=(',',':')).replace('</','<\\/')
 html='''<!doctype html><meta charset=utf-8><title>Scene Brain Library Foundation</title><style>body{background:#09111f;color:#eef2ff;font:15px system-ui;max-width:1300px;margin:auto;padding:18px}table{border-collapse:collapse;width:100%}td,th{padding:9px;border-bottom:1px solid #334155;text-align:left}button{padding:9px}.card{background:#17243a;padding:12px;margin:8px 0}.SEARCHABLE{color:#4ade80}.TRANSCRIPT_REQUIRED{color:#fbbf24}</style><h1>Portable Library Foundation</h1><div id=vol></div><button id=rescan>RESCAN MEDIA DRIVE</button><p id=msg></p><table><thead><tr><th>Title</th><th>Type</th><th>Detected</th><th>Searchable</th><th>Rich</th><th>Needs Transcript</th><th>Errors</th></tr></thead><tbody id=rows></tbody></table><div id=detail></div><script>const D=__DATA__;vol.textContent=`Connected Volume: ${D.manifest.volume_label} · ${D.manifest.scene_brain_volume_id} · Media Root: ${D.manifest.last_resolved_media_root}`;function sum(t,k){return t.sources.filter(x=>x.maturity===k).length}rows.innerHTML=D.titles.map((t,i)=>`<tr data-i=${i}><td>${t.display_name}</td><td>${t.kind}</td><td>${t.sources.length}</td><td>${sum(t,'SEARCHABLE')}</td><td>${sum(t,'RICH_ATLAS_READY')}</td><td>${sum(t,'TRANSCRIPT_REQUIRED')}</td><td>${sum(t,'ERROR')}</td></tr>`).join('');rows.querySelectorAll('tr').forEach(r=>r.onclick=()=>{let t=D.titles[+r.dataset.i];detail.innerHTML=`<h2>${t.display_name}</h2>`+t.sources.map(x=>`<div class="card ${x.maturity}">${x.relative_path}<br>${x.subtitle_status} · ${x.maturity}</div>`).join('')});rescan.onclick=()=>msg.textContent='Run START_LIBRARY_FOUNDATION.bat to perform an incremental rescan and refresh this dashboard.';</script>'''.replace('__DATA__',data);runtime.mkdir(parents=True,exist_ok=True);(runtime/'LIBRARY_FOUNDATION.html').write_text(html,encoding='utf8');(runtime/'START_LIBRARY_FOUNDATION.bat').write_text('@echo off\r\ncd /d "'+str(runtime.parent.parent)+'"\r\npython -m scenebrain.library_cli\r\nstart "FoundationServer" /min python -m http.server 8776 --bind 127.0.0.1 --directory "'+str(runtime)+'"\r\ntimeout /t 2 /nobreak >nul\r\nstart "" http://127.0.0.1:8776/LIBRARY_FOUNDATION.html\r\n',encoding='ascii')
